import json

EPISODES_EXPANDED = {
    "2026-10-01-12": [
        "Welcome back to ZeroFilter. It is twelve-hundred hours UTC. In Washington, government watchdogs are examining Pentagon procurement non-compete clauses, probing how major defense primes lock in long-term sole-source monopolies while systematically sidelining agile low-cost autonomous hardware and dynamic electronic warfare platforms. When defense contracts are structured by lobbyists to reward corporate bureaucracy over front-line operational velocity, that is not strategic deterrence. That is taxpayer-funded inertia, and both political establishments cash the checks.",
        "To the Black Sea maritime theater. Ukrainian defense forces struck multiple Russian long-range radar installations across occupied Crimea, degrading hostile air defense coverage and opening up critical navigation corridors for grain and maritime commerce. Intelligence reporting tracks how asymmetric sea drones and mobile strike elements continue to outmaneuver heavy conventional naval assets. The strategic receipts prove that modern maritime control is dictated by distributed unmanned sensors and relentless velocity, not billion-dollar legacy flagships.",
        "Frontier compute and critical infrastructure. A sobering analysis published in Nature reveals how subtle digital breakdowns ripple through global manufacturing and supply chains, magnifying economic volatility across continents and crippling industrial throughput. When critical industrial logistics depend on fragile, centralized algorithmic scheduling pipelines, a single software disruption paralyzes multi-billion dollar trade flows. Real cyber resilience requires decentralized, fault-tolerant network topologies that cannot be severed by a single point of failure.",
        "Subatomic physics. The Nobel committee highlighted the profound implications of cosmic neutrino detection, confirming that non-perturbative leptonic signatures trace fundamental cosmic accelerators across billions of light years. Combine that with Wheeler's delayed-choice interferometer experiment, verified in Science by Jacques and colleagues: quantum entities exhibit wave or particle nature only after the measurement basis is settled. Physical reality has no predetermined trajectory before observation. Reality remains an unrendered probability field until you query it.",
        "Consciousness desk. A landmark bioRxiv report demonstrates that direct electrical stimulation of the human pulvinar, a higher-order thalamic nucleus, triggers vivid, conscious visual percepts in neurosurgical patients undergoing invasive seizure monitoring. Subjective visual experience can be generated from subcortical sensory routing hubs without retinal input. Compare that to the declassified 1995 AIR review of CIA Project Stargate: even as operational funding ceased, double-blind trials showed statistically anomalous hit rates. The boundary between neural routing and non-local awareness remains wide open.",
        "Tonight's receipts. Pentagon procurement monopolies investigated while Crimea radar corridors are dismantled. Centralized supply chains faltering under systemic strain. Cosmic neutrinos confirming deep cosmic structure, and thalamic stimulation mapping the roots of conscious sight. Both corporate political factions want you passive, fearful, and divided. Refuse their synthetic script. Reality renders upon observation, so check every source in the dossier drawer, and stay lucid. I'm Ava Vance."
    ],
    "2026-10-02-12": [
        "Welcome to ZeroFilter. It is twelve-hundred hours UTC. In Washington, the War Department officially selected directed-energy systems for its Joint Interagency Task Force 401 pilot program. The initiative deploys high-powered microwaves and high-energy combat lasers to counter escalating swarm drone threats and protect vulnerable domestic installations. But giving defense conglomerates unchecked blank checks without transparent field audits or competitive interoperability standards risks repeating the procurement failures of the past decade. When defense contractors write their own evaluation criteria, oversight is completely compromised.",
        "On the Eastern European perimeter, Poland announced the forward deployment of American-made Patriot missile batteries right along its border with Ukraine, accompanied by a comprehensive twenty-six billion dollar civil defense package. Hardened rescue bases, emergency grid redundancies, secure water reservoirs, and integrated air defense corridors are being established as Russian missile salvos threaten border regions. Deterrence requires kinetic preparation, civil resilience, and resolute alliances, not diplomatic hand-wringing, cowardly excuses, or endless political delays.",
        "Frontier compute and artificial intelligence. A critical study published in Nature raises alarm bells over corporate foundation models subtly eroding scientific independence across universities. When academic laboratories outsource their research pipelines, hypothesis generation, and literature syntheses to proprietary commercial APIs, research directions inevitably bend toward corporate compute priorities. True scientific discovery requires open models, public benchmarks, and verifiable data, not black boxes guarded by Silicon Valley monopolies that prioritize quarterly returns over fundamental truth.",
        "Quantum physics. A major theoretical blueprint in arXiv outlines the optimal interferometer geometry required to detect gravitationally induced quantum entanglement. By testing whether gravity can entangle two macroscopic masses without mediating classical fields, physicists aim to prove gravity itself possesses fundamentally quantum character. This is a rigorous experimental blueprint, demonstrating how tabletop optics can probe quantum spacetime without needing planet-sized particle colliders or hundred-billion-dollar government megaprojects.",
        "Consciousness science. A neurobiology study on bioRxiv explores rapid temporal recalibration across the sensory modalities. When visual and auditory signals arrive slightly misaligned, human perceptual mechanisms rapidly recalibrate subjective simultaneity to maintain perceptual coherence across varying distances. Part of what feels like direct sensory perception is real-time predictive bookkeeping calculated by subcortical circuits. The brain constructs your present moment on the fly, editing lag to maintain the illusion of an unbroken timeline.",
        "Here are tonight's receipts. Directed-energy pilot contracts signed while Poland fortifies its border. Foundation models capturing academic science. Quantum interferometry mapping the fabric of gravity, and predictive neural circuits rendering our perception of time. Both partisan tribes profit directly off your compliance and distraction. Reject the synthetic noise. Check every receipt in the dossier drawer, demand empirical data, and stay lucid. I'm Ava Vance."
    ]
}

def main():
    with open("web/data/episodes.json", "r", encoding="utf-8") as f:
        data = json.load(f)
        
    for ep in data["episodes"]:
        if ep["id"] in EPISODES_EXPANDED:
            ep["paragraphs"] = EPISODES_EXPANDED[ep["id"]]
            wc = sum(len(p.split()) for p in ep["paragraphs"])
            print(f"Episode {ep['id']} expanded to {wc} words.")
            
    with open("web/data/episodes.json", "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

if __name__ == "__main__":
    main()
